apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: {{ .Values.kafka.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.kafka.port }}
      targetPort: {{ .Values.kafka.targetPort }}